version: '3.1'
services:
  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 8080:8080
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: 123
    ports:
     - 3306:3306
     - 33060:33060
  backend:
    image: backend
    restart: always
    ports:
     - 4000:4000